/* Generated By:JJTree: Do not edit this line. ASTfore.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ru.nsu.ci.translator;

public
class ASTfore extends SimpleNode {
  public ASTfore(int id) {
    super(id);
  }

  public ASTfore(SI p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SIVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ecef5df5bd378c8dfdb6cf3263c47537 (do not edit this line) */
