/* Generated By:JJTree: Do not edit this line. ASTfore.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=ru.nsu.ci.RubicNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ru.nsu.ci.translator;

public
class ASTfore extends SimpleNode {
  public ASTfore(int id) {
    super(id);
  }

  public ASTfore(SI p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SIVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dea7ff9f2eaa3287b0b693b6ad19caa0 (do not edit this line) */
