/* Generated By:JJTree: Do not edit this line. ASTrestart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=ru.nsu.ci.RubicNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ru.nsu.ci.translator;

public
class ASTrestart extends SimpleNode {
  public ASTrestart(int id) {
    super(id);
  }

  public ASTrestart(SI p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SIVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6e344e65c8d421a963a3a309cafae803 (do not edit this line) */
