/* Generated By:JJTree: Do not edit this line. ASTturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=ru.nsu.ci.RubicNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ru.nsu.ci.translator;

public
class ASTturn extends SimpleNode {
  public ASTturn(int id) {
    super(id);
  }

  public ASTturn(SI p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SIVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9bac7662ff09de3a5c21aba23175b38a (do not edit this line) */
