/* Generated By:JJTree: Do not edit this line. ASTtemp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=ru.nsu.ci.RubicNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ru.nsu.ci.translator;

public
class ASTtemp extends SimpleNode {
  public ASTtemp(int id) {
    super(id);
  }

  public ASTtemp(SI p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SIVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=376814c5034b1408ec297f13b07b551c (do not edit this line) */
