/* Generated By:JJTree&JavaCC: Do not edit this line. SIConstants.java */
package ru.nsu.ci.translator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SIConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int POCH = 4;
  /** RegularExpression Id. */
  int PRCH = 5;
  /** RegularExpression Id. */
  int TURN = 6;
  /** RegularExpression Id. */
  int LETTER = 7;
  /** RegularExpression Id. */
  int MOV = 8;
  /** RegularExpression Id. */
  int FOR = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int RESTART = 11;
  /** RegularExpression Id. */
  int CANCEL = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "<NUMBER>",
    "\"\\u0420\\u0457\\u0420\\u0455\\u0420\\u00a7\\u0420\\u00b0\\u0421\\u0403\\u0420\\u0455\\u0420\\u0406\\u0420\\u0455\\u0420\\u2116\"",
    "\"\\u0420\\u0457\\u0421\\u0402\\u0420\\u00a7\\u0420\\u00b0\\u0421\\u0403\\u0420\\u0455\\u0420\\u0406\\u0420\\u0455\\u0420\\u2116\"",
    "\"\\u0420\\u0457\\u0420\\u0455\\u0420\\u0406\\u0420\\u00b5\\u0421\\u0402\\u0420\\u0405\\u0421\\u0453\\u0421\\u201a\\u0421\\u040a\"",
    "<LETTER>",
    "\"\\u0420\\u0457\\u0420\\u00b5\\u0421\\u0402\\u0420\\u00b5\\u0420\\u2116\\u0421\\u201a\\u0420\\u0451\"",
    "\"\\u0420\\u0457\\u0420\\u0455\\u0420\\u0406\\u0421\\u201a\\u0420\\u0455\\u0421\\u0402\\u0420\\u0451\\u0421\\u201a\\u0421\\u040a\"",
    "\"\\u0421\\u0402\\u0420\\u00b0\\u0420\\u00b7\"",
    "\"\\u0420\\u00b7\\u0420\\u00b0\\u0420\\u0405\\u0420\\u0455\\u0420\\u0406\\u0420\\u0455\"",
    "\"\\u0420\\u0455\\u0421\\u201a\\u0420\\u0458\\u0420\\u00b5\\u0420\\u0405\\u0420\\u0451\\u0421\\u201a\\u0421\\u040a\"",
  };

}
