/* Generated By:JJTree&JavaCC: Do not edit this line. SIConstants.java */
package ru.nsu.ci.translator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SIConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int NUMBER = 3;
  /** RegularExpression Id. */
  int TURN = 4;
  /** RegularExpression Id. */
  int LETTER = 5;
  /** RegularExpression Id. */
  int MOV = 6;
  /** RegularExpression Id. */
  int FOR = 7;
  /** RegularExpression Id. */
  int END = 8;
  /** RegularExpression Id. */
  int RESTART = 9;
  /** RegularExpression Id. */
  int CANCEL = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "<NUMBER>",
    "\"TURN\"",
    "<LETTER>",
    "\"MOV\"",
    "\"FOR\"",
    "\"END\"",
    "\"RESTART\"",
    "\"CANCEL\"",
  };

}
