/* Generated By:JavaCC: Do not edit this line. SITreeConstants.java Version 5.0 */
package ru.nsu.ci.translator;

public interface SITreeConstants
{
  public int JJTSTART = 0;


  public String[] jjtNodeName = {
    "start",
  };
}
/* JavaCC - OriginalChecksum=d9e1d85a2a5e680d2857776514dd09ab (do not edit this line) */
