/* Generated By:JavaCC: Do not edit this line. SITreeConstants.java Version 5.0 */
package ru.nsu.ci.translator;

public interface SITreeConstants
{
  public int JJTVOID = 0;
  public int JJTTURN = 1;
  public int JJTMOV = 2;
  public int JJTFORE = 3;
  public int JJTCANCEL = 4;
  public int JJTRESTART = 5;
  public int JJTTEMP = 6;


  public String[] jjtNodeName = {
    "void",
    "turn",
    "mov",
    "fore",
    "cancel",
    "restart",
    "temp",
  };
}
/* JavaCC - OriginalChecksum=e5b8913d9dadc7ea4d01b0305968da49 (do not edit this line) */
