/* Generated By:JavaCC: Do not edit this line. SIVisitor.java Version 5.0 */
package ru.nsu.ci.translator;

public interface SIVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTturn node, Object data);
  public Object visit(ASTmov node, Object data);
  public Object visit(ASTfore node, Object data);
  public Object visit(ASTcancel node, Object data);
  public Object visit(ASTrestart node, Object data);
}
/* JavaCC - OriginalChecksum=e6d1eae7d381d1cb3c554fed02b99808 (do not edit this line) */
