/* Generated By:JavaCC: Do not edit this line. SIVisitor.java Version 5.0 */
package ru.nsu.ci.translator;

public interface SIVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTturn node, Object data);
  public Object visit(ASTmov node, Object data);
  public Object visit(ASTfore node, Object data);
  public Object visit(ASTcancel node, Object data);
  public Object visit(ASTrestart node, Object data);
  public Object visit(ASTtemp node, Object data);
}
/* JavaCC - OriginalChecksum=2195d78a4c7337c5fdffd40c6d40557c (do not edit this line) */
